### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by benschwarz** [jmaferreira/easy_xiaomi_tokens#1]
Hey @jmaferreira, I took this for a spin and met an error that I wasn't able to get past: 

```
❯ npm start

> easy_xiaomi_tokens@1.0.0 start /Users/benschwarz/Desktop/easy_xiaomi_tokens
> node index.js

/Users/benschwarz/Library/Application Support/MobileSync/Backup/
(node:74147) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, scandir '/Users/benschwarz/Library/Application Support/MobileSync/Backup/'
    at Object.readdirSync (fs.js:854:3)
    at /Users/benschwarz/Desktop/easy_xiaomi_tokens/node_modules/ibackuptool/tools/reports/backups/list.js:11:22
    at new Promise (<anonymous>)
    at Object.run (/Users/benschwarz/Desktop/easy_xiaomi_tokens/node_modules/ibackuptool/tools/reports/backups/list.js:9:12)
    at /Users/benschwarz/Desktop/easy_xiaomi_tokens/node_modules/ibackuptool/tools/index.js:190:12
    at new Promise (<anonymous>)
    at runReport (/Users/benschwarz/Desktop/easy_xiaomi_tokens/node_modules/ibackuptool/tools/index.js:167:10)
    at /Users/benschwarz/Desktop/easy_xiaomi_tokens/node_modules/ibackuptool/tools/index.js:149:26
(node:74147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:74147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The `MobileSync` directory on my machine was from 2014 so I removed it and created a fresh new backup. Is there maybe an undocumented step that I'll need to follow to have this library work?

**Comment by benschwarz** [comment]
Ah! Got it. 

You need to enable terminal full disk access. 
https://www.npmjs.com/package/ibackuptool#terminal-permissions-macos

Maybe worth adding to the README?

**Comment by jmaferreira** [comment]
Absolutely. Thanks.
